---
apiVersion: v1
kind: Pod
metadata:
  name: garden-setup-uninstaller
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: garden-setup-installer
      image: 'diaphteiros/garden-setup:stable'
      imagePullPolicy: Always
      command:
        - ./run.sh
        - '--color'
        - delete
        - '-A'
      resources: {}
      volumeMounts:
        - name: garden-setup-config
          mountPath: /etc/garden-setup/config
        - name: garden-setup-state
          mountPath: /landscape
  volumes:
    - name: garden-setup-config
      secret:
        secretName: garden-setup-config
    - name: garden-setup-state
      persistentVolumeClaim:
        claimName: garden-setup-state
