---
apiVersion: v1
kind: Secret
metadata:
  name: garden-setup-config
  namespace: default
type: Opaque
data:
  kubeconfig: >-
    YXBpVmVyc2lvbjogdjENCmNsdXN0ZXJzOg0KLSBjbHVzdGVyOg0KICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBEQVRBK09NSVRURUQNCiAgICBzZXJ2ZXI6IGh0dHBzOi8vMzUuMTkzLjEzMS4yNTQNCiAgbmFtZTogZ2tlX2dhcmRlbmVyLTI2MDMxNl91cy1jZW50cmFsMS1hX2drZS1nYXJkDQpjb250ZXh0czoNCi0gY29udGV4dDoNCiAgICBjbHVzdGVyOiBna2VfZ2FyZGVuZXItMjYwMzE2X3VzLWNlbnRyYWwxLWFfZ2tlLWdhcmQNCiAgICB1c2VyOiBna2VfZ2FyZGVuZXItMjYwMzE2X3VzLWNlbnRyYWwxLWFfZ2tlLWdhcmQNCiAgbmFtZTogZ2tlX2dhcmRlbmVyLTI2MDMxNl91cy1jZW50cmFsMS1hX2drZS1nYXJkDQogIGN1cnJlbnQtY29udGV4dDogZ2tlX2dhcmRlbmVyLTI2MDMxNl91cy1jZW50cmFsMS1hX2drZS1nYXJkDQpraW5kOiBDb25maWcNCnByZWZlcmVuY2VzOiB7fQ0KdXNlcnM6DQotIG5hbWU6IGdrZV9nYXJkZW5lci0yNjAzMTZfdXMtY2VudHJhbDEtYV9na2UtZ2FyZA0KICB1c2VyOg0KICAgIHVzZXJuYW1lOiBhZG1pbg0KICAgIHBhc3N3b3JkOiBIVG5FNHZ6QldJV2R0NkJSDQo=
  acre.yaml: >-
    Y3JlZGVudGlhbHM6ICZyZWZfMAogIHNlcnZpY2VhY2NvdW50Lmpzb246IHwKICAgIHsKICAgICAgInR5cGUiOiAic2VydmljZV9hY2NvdW50IiwKICAgICAgInByb2plY3RfaWQiOiAiZ2FyZGVuZXItMjYwMzE2IiwKICAgICAgInByaXZhdGVfa2V5X2lkIjogIjRjZGFiZjNiYTkzOTAyN2NiNWY2YzgyZjI3ZGM1ZGQ2N2QxYmU0NWUiLAogICAgICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURmam90VUxYNVIwUmJYXG41N3lYNEc0SEx6K2RHWk93Q2FucHFuclI4K1ZveCt1T0QwTUxwTjNVdjllRUlxWml3TklkREhrS2x4SnpTaDRCXG5MZ1hNMW81WVRNYUxwbXNKSVBtczJvUiswWHpYYXBURGtZcllHcVBmOU9JNExmb1JDQnFJdjhDRFN0cWVOUVNjXG5pRjNBL1d1UDFTT29PRmxMRWt1TCtNYXh1bW5NRDNZOUpYcWU0eW1uYjRtei9tSWZ5d0VjU3ZhQTNtaFhpdDd4XG4wNlZyeXcvUVJwUWRRTGxzcDMwWjhSb3diR3dPNHZTYXN5ZDJZWFVBNU9wL0hFWFdYTWdFekhOaU5TamZUcGh0XG5iZ081ZG0zQXhjMDk2YXU0T0JEdGZNb1NuZTltd3EvemRtWVBhaTJlaUIrcVlmbCt3M1l0cHhXVWJRUXFEcnNEXG4rckhodDdvSEFnTUJBQUVDZ2dFQVk5dXVUTW1OZFVwcVk4SzFzVG1rckR6a3MyM3JWR1RjcXUxbHMwYTRvSmM4XG5sdFltWXBzZ0k1b1YwSVlSd0diVTgvalFVSFN1M3lTcVJtaWlXcDgwTWlrSlB2UDFON3l0Q2hNSndBUWZPYkg0XG5CV3VMazRCQzF4VHh2NXA1NndXdHBJdlNtRkxsV0duaVIzRjZQMnh6a1ducFpZaldDZnlBRm1QbmpSZnhqaDQ3XG44eHRNdjBndVNGeU9peEsxL3N0TUw1M2tmRHFVbnNXUUNrS2hqeG5VdEVVKzJWTGdpWm81enRBYTJINWtJVTkvXG5lMXNtVnBPZkgvYnNvcnl3T2MraDY4bkVzYVBaRjJHZjk4OE53alhoZDlTV3pkMVhZSjlKNyt2QUM3Ry9pV3YvXG5KUWdqY3FWN3o0dGZzUzljMFhBMW4ra3RTcTYxVUk0WjRaZUc2RTVTSVFLQmdRRDhRNk5SN0lRc0REcjVwenpNXG5lN0FTN0Y0WHJLZDBFcFQ0SXgxZzd4aDkrOThuNS9oczM0KzhvcFVWOE5rQXBlZmpRQjJoY01GS2JQN2Q4bGN3XG5YeTAzVmxCOGJZS2l0YUZwSGtocEp2NDRUOCtnZWx2dHhHQW9HRFkrM1JqQ0tjYWlSUjJYNnExNE5menIvbXE1XG5mbUpwaUsxM2kwek1WWGhqNjBlbFNCZXIzd0tCZ1FEaTNoTEVWYUdoalZRVzBCdVBrNHhsZnRiUWt0aHkzZnB4XG5Ib3d3Ti9lc2phelpEM2k2MXFHWVZkVC9WQlNxSmlldGVwcEVGbDBseFlqYmd0ZHNINjlaVUVUTUY5MW5LTytIXG5udWpVZ1ZVazd1eHRhNCtEM21tVUE0NS9aQWNaUEt5Qkd3U2ZQd1F2bWZvM2tTMzFYVzhhSEZHOUVHSlk5bmhwXG5RUExyQlZvMjJRS0JnUUNEaThYYno2a3d5d1BwOGRLYmt4aERGZTBQRFdLWS9hT2ZMYmlCTnMwZnpUc1dOVG52XG5sRGtCRmdzR1VQem9BSnZHZmtXMVRQWU9tSDNqUVI5RVF5MXlBTm1odVAxNVdadWRGRVNRU053aWcwUHpIRHRaXG41cUI1NS81Sms4UDRaQTZIeWVEZnVtblJHTjRXTmlwekpqdXRhcStDZWlxSEZ6N2JZL0tOZHVXWkl3S0JnSDVPXG5Velo1MGxZR1FDVy9VVWpiUmRRUURQcnNkcE5sSUpTd0JDNm9TajBJVjQ0MWZlclBxZ0lNNzF3RDdNbGFHc2NMXG50aTFvSWczd2J5Ui9NUDVpbVpacENSUnp5UEV4S2tKZ1o1SkFPeTRuMHZ1TVljZHlJV2VsbjBVdlpJQlpkbFVlXG52TEVJUFlWZS9aN0lOa1VmOHNZZnRDWkZvK3VSdFRJc1ZkSWhGYnZwQW9HQUp5NnFtaVkyTks5RE9ZODFScnphXG4xQWJuLzZyM2tYNWp3YSt2ckFwQldkSXNaei8yaXV3S2VCUTUyd0tzaTZjTGpwQldneTN0Si9zS0ltd1F3a0EzXG5EaGpOQ1k3YVZ2ZmhhRytBVDBrL2I0TUN6MmdaS0swci9yNTVlZXJYZWFPWVpxUVhmejh2RkEwZlpBVU1kaFV4XG53RGNSWGEzN05JUnRNZ1JqT21pNnY1bz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgICAgICJjbGllbnRfZW1haWwiOiAiNjU1NjI4NDY4MDAxLWNvbXB1dGVAZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICAgICAiY2xpZW50X2lkIjogIjExMDAwMTEwMDI3MDA2NzYxNjg0NSIsCiAgICAgICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgICAgICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICAgICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgICAgICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5LzY1NTYyODQ2ODAwMS1jb21wdXRlJTQwZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iCiAgICB9CmxhbmRzY2FwZToKICBuYW1lOiBna2UtZ2FyZC10ZXN0LWNvbQogIGNsdXN0ZXI6CiAgICBrdWJlY29uZmlnOiAuL2t1YmVjb25maWcKICAgIGRvbWFpbjogZ2tlLWdhcmQudGVzdC5jb20KICAgIGlhYXM6IGdjcAogICAgcmVnaW9uOiB1cy1jZW50cmFsMQogIG5ldHdvcmtzOgogICAgcG9kczogMTAuMTIuMC4wLzE0CiAgICBub2RlczogMTAuMTI4LjAuMC8yMAogICAgc2VydmljZXM6IDEwLjE2LjAuMC8yMAogIGlhYXM6CiAgICByZWdpb246IHVzLWNlbnRyYWwxCiAgICB6b25lczoKICAgICAgLSB1cy1jZW50cmFsMS1hCiAgICBjcmVkZW50aWFsczogKnJlZl8wCiAgZXRjZDoKICAgIGJhY2t1cDoKICAgICAgdHlwZTogZ2NzCiAgICAgIHJlZ2lvbjogdXMtY2VudHJhbDEKICAgICAgY3JlZGVudGlhbHM6ICpyZWZfMAogIGRuczoKICAgIHR5cGU6IGdvb2dsZS1jbG91ZGRucwogICAgY3JlZGVudGlhbHM6ICpyZWZfMAogIGlkZW50aXR5OgogICAgdXNlcnM6CiAgICAgIC0gZW1haWw6IGluc3RhbGxlckB0ZXN0LmNvbQogICAgICAgIHVzZXJuYW1lOiBpbnN0YWxsZXJAdGVzdC5jb20KICAgICAgICBwYXNzd29yZDogUm95YWxDeWJlcjEyMwo=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garden-setup-state
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: garden-setup-installer
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: garden-setup-installer
      image: 'diaphteiros/garden-setup:stable'
      imagePullPolicy: Always
      command:
        - ./run.sh
        - '--color'
        - deploy
        - '-An'
      resources: {}
      volumeMounts:
        - name: garden-setup-config
          mountPath: /etc/garden-setup/config
        - name: garden-setup-state
          mountPath: /landscape
  volumes:
    - name: garden-setup-config
      secret:
        secretName: garden-setup-config
    - name: garden-setup-state
      persistentVolumeClaim:
        claimName: garden-setup-state
